"""Wave 19 public-key authenticity proof."""

from .auth2 import (
    ALG_ECDSA_P256_SHA256,
    ENVELOPE_HEADER_SIZE,
    ENVELOPE_SIGNATURE_OFFSET,
    MANIFEST_HEADER_SIZE,
    MANIFEST_SIGNATURE_OFFSET,
    P256_ORDER,
    ROLE_RECOVERY,
    ROLE_RELEASE,
    Auth2Error,
    KeyPolicy,
    Manifest,
    ManifestKey,
    VerifiedEnvelope,
    build_manifest,
    ecdsa_raw_to_der,
    envelope_signing_bytes,
    key_id_from_public_key,
    manifest_signing_bytes,
    sign_envelope,
    verify_envelope,
    verify_manifest,
)

__all__ = [
    "ALG_ECDSA_P256_SHA256",
    "ENVELOPE_HEADER_SIZE",
    "ENVELOPE_SIGNATURE_OFFSET",
    "MANIFEST_HEADER_SIZE",
    "MANIFEST_SIGNATURE_OFFSET",
    "P256_ORDER",
    "ROLE_RECOVERY",
    "ROLE_RELEASE",
    "Auth2Error",
    "KeyPolicy",
    "Manifest",
    "ManifestKey",
    "VerifiedEnvelope",
    "build_manifest",
    "ecdsa_raw_to_der",
    "envelope_signing_bytes",
    "key_id_from_public_key",
    "manifest_signing_bytes",
    "sign_envelope",
    "verify_envelope",
    "verify_manifest",
]
